services:
  - type: web
    name: backend-saas
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DB_HOST
        value: hopper.proxy.rlwy.net
      - key: DB_PORT
        value: 57218
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: bLFNXiHRbOvKNRHbMPwZXJPeCmjGTAtK
      - key: DB_NAME
        value: railway
      - key: JWT_SECRET
        value: supersecreto123 